### ISSUE TITLE
Mock GLOBAL::glob

### ISSUE THREAD

**Issue by toddr** [cpanel/Test-MockFile#40]

**Comment by atoomic** [comment]
supporting `glob` would be a nice feature
```perl
my $mock_dir = Test::MockFile->dir( "/not-there", [ qw{foo bar} ] );
note explain [ glob("/not-there/*") ];
```

**Comment by drmuey** [comment]
This is actually pretty critical because real data can be lost:

```
my $mock_dir = Test::MockFile->dir( "/etc/important/", [ qw{foo.conf bar.conf} ] );
baz();
… "baz() cleans out /etc/important/";
```

say `baz()` accomplished that w/ `unlink(glob "/etc/important/*conf")`.

even though `/etc/important/` is mocked, the actual `/etc/important/` is what gets acted on. i.e. real files get deleted.

**Comment by drmuey** [comment]
+1

**Comment by xsawyerx** [comment]
I've provided an implementation for it in #68.

**Comment by xsawyerx** [comment]
Resolved.
