### ISSUE TITLE
fileno unimplemented

### ISSUE THREAD

**Issue by dchisolm** [cpanel/Test-MockFile#45]
Ran into a case today where having fileno implemented would have been great for BoxTrapper::CORE. 

Thanks

**Comment by FGasper** [comment]
How would this work? The point of Test::MF is precisely that there _is_ no underlying file descriptor.

**Comment by toddr** [comment]
Randomly pick a number above 30 and below 1024? Check via posix if it handle is open?

Sure, someone could come along and use it out from under you. But I suspect it would be unlikely to affect the test

**Comment by toddr** [comment]
The code just needs to be filled in here https://github.com/CpanelInc/Test-MockFile/blob/master/lib/Test/MockFile/FileHandle.pm#L350

**Comment by FGasper** [comment]
I suppose that would facilitate same-filehandle checks, so I could see that being useful. It seems seems pretty edge-y and not unlikely to lead to misuse and/or confusion.

**Comment by toddr** [comment]
I can't come up with anything positive you might do with fileno that might not lead to side effects.

I might be ok with us dieing in strict mode if fileno is called as this is unsupported for anything mocked.

**Comment by FGasper** [comment]
Yeah I’d think die()ing. There _is_ no file descriptor for these filehandles; if you need a “real” test filehandle, use File::Temp?

**Comment by toddr** [comment]
We could do File::Temp but let's do die first and then if people want it, we'll think about enabling File::Temp on-demand if people need fileno for tests. Honestly, fileno is kinda a rare call in most code bases.

**Comment by FGasper** [comment]
I meant that the caller could do File::Temp. Seems out of scope for this library.
