### ISSUE TITLE
opendir w/ a bare handle throws a strict refs error

### ISSUE THREAD

**Issue by drmuey** [cpanel/Test-MockFile#47]
1. Create `TestMe.pm` somewhere in `@INC`.
```
package TestMe;

use strict;
use warnings;

sub dir {
    opendir DH, ".";
}

1;
```
2. perl -e 'use Test::MockFile;use TestMe;print TestMe::dir();'
3. note the error:
> Can't use string ("DH") as a symbol ref while "strict refs" in use at …

While we could update TestMe.pm (w/ a `no strict "refs";` before the `opendir` or better yet to not use a bareword handle) that won't help anyone who needs to use a module they have no control over.

**Comment by toddr** [comment]
I agree this is a problem. Can you give me an example of something on CPAN you would want mocked where this is actually a problem?

**Comment by cPanelChrisD** [comment]
This can be reproduced using the core module File::Find:
```
# perl -MTest::MockFile -MFile::Find -e 'find(sub { }, q(/tmp))'
Can't use string ("DIR") as a symbol ref while "strict refs" in use at /usr/local/cpanel/3rdparty/perl/532/lib/perl5/532/File/Find.pm line 386.
```

**Comment by toddr** [comment]
I'll work on fixing this. Barewords are not easily fixed. I'd rather fix File::Find.

**Comment by xsawyerx** [comment]
I provide a fix with a *very* long explanation here: https://github.com/cpanel/Test-MockFile/pull/60. My apologies. :)

**Comment by toddr** [comment]
Before
```
$>perl -Ilib -e 'use Test::MockFile;use TestMe;print TestMe::dir();'
Can't use string ("DH") as a symbol ref while "strict refs" in use at lib/TestMe.pm line 7.
```

After c96b8d37ba1de55a2ca1aeca2ccb1b92ff973ed0, there is no output as it doesn't error.
