### ISSUE TITLE
Conflict with Test::Pod::Coverage

### ISSUE THREAD

**Issue by adamgsg** [cpanel/Test-MockFile#48]
Adding Test::MockFile to my test produces this error:

\# Can't use string ("DH") as a symbol ref while "strict refs" in use at lib/perl5/Test/Pod/Coverage.pm line 219.
    # Failed test 'all_pod_coverage_ok'
    # at lib/perl5/Test2/Tools/AsyncSubtest.pm line 23.

This is happening with the latest version of Test::Pod::Coverage (1.10) and Test::MockFile (0.019)

**Comment by toddr** [comment]
Wouldn't that make this an issue with those modules? Have you opened ticket(s) there?

**Comment by toddr** [comment]
This is fixed by c96b8d37ba1de55a2ca1aeca2ccb1b92ff973ed0 and should be in the 0.022 release.
