### ISSUE TITLE
Use current uid/gid when creating temporary files

### ISSUE THREAD

**Issue by atoomic** [cpanel/Test-MockFile#51]
We should use the current user and group  id when creating a file unless provided

When running this code as a non root user it fails, because the uid and gid are set to 0
{code} 
> id
uid=1003(foopl) gid=1003(foopl) groups=1003(foopl)
> perl -MTest::MockFile -e'my $path = "/tmp/fake"; my $f = Test::MockFile->file( $path, " ", { mode => 0700 } ); print( ( -x $path) . $/ ); printf "mode: 0%o\n", (stat $path)[2]'

mode: 0100702
{code} 

Of course we could do something like this `uid => $>` but that should be the default behavior when not set
{code} 
perl -MTest::MockFile -e'my $path = "/tmp/fake"; my $f = Test::MockFile->file( $path, " ", { mode => 0700, uid => $> } ); print( ( -x $path) . $/ ); printf "mode: 0%o\n", (stat $path)[2]'
1
mode: 0100702
{code}

**Comment by atoomic** [comment]
I'm going to provide a fix for this

**Comment by toddr** [comment]
The functionality of user/group has not really been meaningfully provided in the code. I consider that a significant amount of work.

**Comment by xsawyerx** [comment]
I think it's best if we close this ticket in favor of more granular tickets for specific UID/GID issues.

**Comment by toddr** [comment]
agreed
